<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-DCLC66P" failures="1" tests="5" name="Test" time="68.497" errors="0" timestamp="2024-06-29T12:53:06 IST">
  <testcase classname="TestCases.ApplyJob" name="login" time="7.259"/>
  <testcase classname="TestCases.ApplyJob" name="udateResume" time="43.623">
    <failure type="java.lang.AssertionError" message="expected [Resume Headline has been successfully saved.] but found [Resume has been successfully uploaded.]">
      <![CDATA[java.lang.AssertionError: expected [Resume Headline has been successfully saved.] but found [Resume has been successfully uploaded.]
at TestCases.ApplyJob.udateResume(ApplyJob.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- udateResume -->
  <testcase classname="TestCases.ApplyJob" name="updateSummery" time="3.674"/>
  <testcase classname="TestCases.ApplyJob" name="updateSkills" time="2.248"/>
  <testcase classname="TestCases.ApplyJob" name="logout" time="0.406"/>
</testsuite> <!-- Test -->
